### ISSUE TITLE
More information about rust.vim

### ISSUE THREAD

**Issue by tafia** [ivanceras/rust-vim-setup#1]
I think rust.vim is a lot more powerful than just syntax highlighting.
Unfortunately I can't find a documentation for it but looking.

**Comment by kenshinji** [comment]
Since vim has a powerful help doc system, I guess you can try looking the help doc of rust.vim. If you don't know how to check help doc of vim plugin, I suggest you check [this](http://superuser.com/questions/260539/how-to-open-the-doc-file-for-a-vim-plugin) out.
